// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.alg.flibusta.latest.domain;

import com.alg.flibusta.latest.domain.NewItems;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NewItems_Roo_Configurable {
    
    declare @type: NewItems: @Configurable;
    
}
