// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.alg.flibusta.latest.domain;

import com.alg.flibusta.latest.domain.NewItem;
import com.alg.flibusta.latest.domain.NewItemDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NewItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NewItemDataOnDemand: @Component;
    
    private Random NewItemDataOnDemand.rnd = new SecureRandom();
    
    private List<NewItem> NewItemDataOnDemand.data;
    
    public NewItem NewItemDataOnDemand.getNewTransientNewItem(int index) {
        NewItem obj = new NewItem();
        setAuthor(obj, index);
        setCategories(obj, index);
        setContent(obj, index);
        setIdTagBook(obj, index);
        setTitle(obj, index);
        setUpdated(obj, index);
        return obj;
    }
    
    public void NewItemDataOnDemand.setAuthor(NewItem obj, int index) {
        String author = "author_" + index;
        obj.setAuthor(author);
    }
    
    public void NewItemDataOnDemand.setCategories(NewItem obj, int index) {
        String categories = "categories_" + index;
        if (categories.length() > 999) {
            categories = categories.substring(0, 999);
        }
        obj.setCategories(categories);
    }
    
    public void NewItemDataOnDemand.setContent(NewItem obj, int index) {
        String content = "content_" + index;
        if (content.length() > 4000) {
            content = content.substring(0, 4000);
        }
        obj.setContent(content);
    }
    
    public void NewItemDataOnDemand.setIdTagBook(NewItem obj, int index) {
        Integer idTagBook = new Integer(index);
        obj.setIdTagBook(idTagBook);
    }
    
    public void NewItemDataOnDemand.setTitle(NewItem obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void NewItemDataOnDemand.setUpdated(NewItem obj, int index) {
        Date updated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdated(updated);
    }
    
    public NewItem NewItemDataOnDemand.getSpecificNewItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NewItem obj = data.get(index);
        Long id = obj.getId();
        return NewItem.findNewItem(id);
    }
    
    public NewItem NewItemDataOnDemand.getRandomNewItem() {
        init();
        NewItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NewItem.findNewItem(id);
    }
    
    public boolean NewItemDataOnDemand.modifyNewItem(NewItem obj) {
        return false;
    }
    
    public void NewItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NewItem.findNewItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NewItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NewItem>();
        for (int i = 0; i < 10; i++) {
            NewItem obj = getNewTransientNewItem(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
