// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.alg.flibusta.latest.domain;

import com.alg.flibusta.latest.domain.NewItems;
import com.alg.flibusta.latest.domain.NewItemsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NewItemsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NewItemsDataOnDemand: @Component;
    
    private Random NewItemsDataOnDemand.rnd = new SecureRandom();
    
    private List<NewItems> NewItemsDataOnDemand.data;
    
    public NewItems NewItemsDataOnDemand.getNewTransientNewItems(int index) {
        NewItems obj = new NewItems();
        setAuthor(obj, index);
        setCategories(obj, index);
        setContent(obj, index);
        setIdTagBook(obj, index);
        setTitle(obj, index);
        setUpdated(obj, index);
        return obj;
    }
    
    public void NewItemsDataOnDemand.setAuthor(NewItems obj, int index) {
        String author = "author_" + index;
        obj.setAuthor(author);
    }
    
    public void NewItemsDataOnDemand.setCategories(NewItems obj, int index) {
        String categories = "categories_" + index;
        obj.setCategories(categories);
    }
    
    public void NewItemsDataOnDemand.setContent(NewItems obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public void NewItemsDataOnDemand.setIdTagBook(NewItems obj, int index) {
        Integer idTagBook = new Integer(index);
        obj.setIdTagBook(idTagBook);
    }
    
    public void NewItemsDataOnDemand.setTitle(NewItems obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void NewItemsDataOnDemand.setUpdated(NewItems obj, int index) {
        Date updated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdated(updated);
    }
    
    public NewItems NewItemsDataOnDemand.getSpecificNewItems(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NewItems obj = data.get(index);
        Long id = obj.getId();
        return NewItems.findNewItems(id);
    }
    
    public NewItems NewItemsDataOnDemand.getRandomNewItems() {
        init();
        NewItems obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NewItems.findNewItems(id);
    }
    
    public boolean NewItemsDataOnDemand.modifyNewItems(NewItems obj) {
        return false;
    }
    
    public void NewItemsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NewItems.findNewItemsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NewItems' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NewItems>();
        for (int i = 0; i < 10; i++) {
            NewItems obj = getNewTransientNewItems(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
