// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.alg.flibusta.latest.domain;

import com.alg.flibusta.latest.domain.NewItemDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NewItemDataOnDemand_Roo_Configurable {
    
    declare @type: NewItemDataOnDemand: @Configurable;
    
}
